name: secrets-demo
on: [push]
jobs:
  branch-job:
    runs-on: ubuntu-latest
    steps: 
      - shell: bash
        env: 
          MY_SECRET: ${{ secrets.MySecret }}
        run: |
          echo ">$MY_SECRET<"
