name: release-demo
on:
  push:
    branches:
      - main
jobs:
  trunk-job:
      runs-on: ubuntu-latest
      environment: PROD
      steps:
        - shell: bash
          env:
            PROD_SECRET: ${{ secrets.PROD_SECRET }}
            REPO_SECRET: ${{ secrets.MySecret }}
          run: |
            if [[ "$REPO_SECRET" == "$PROD_SECRET" ]]; then
              echo "Hello from same secret"
            else
              echo "Hello from different secrets"
            fi
